fn main() {
    println!("What is my exit status?");

    // TODO:
    // 1. Try panicking instead of printing and check its exit status
    // 2. Then try calling std::process::exit(590); and checking its exit status
}
